---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: botkube
  labels:
    component: controller
    app: botkube
spec:
  template:
    spec:
      containers:
        - name: botkube
          image: "infracloud/botkube:v0.7.0"          
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: BOTKUBE_VERSION
              value: v0.7.0
            - name: PROXY
              valueFrom:
                configMapKeyRef:
                  key: PROXY
                  name: proxyconfig
                  optional: false
            - name: HTTPS_PROXY
              value: $(PROXY)
            - name: https_proxy
              value: $(PROXY)              
            - name: no_proxy
              value: $(KUBERNETES_PORT_443_TCP_ADDR)              
